# Generated by Django 4.0.4 on 2022-06-27 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_categoria_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoproduto',
            old_name='produto_id',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
