# Generated by Django 4.0.4 on 2022-06-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_rename_produto_id_fotoproduto_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproduto',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
