# Generated by Django 4.0.4 on 2022-06-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_fotoproduto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoproduto',
            name='foto',
            field=models.FileField(upload_to='produtos'),
        ),
    ]
