# Generated by Django 4.0.4 on 2022-06-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_produto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
